# GitLeaks configuration to detect secrets
[extend]
useDefault = true

[rules.safebreach-api-token]
description = "SafeBreach API Token"
id = "safebreach-api-token"
regex = '''[a-zA-Z0-9_-]{43}'''
tags = ["key", "SafeBreach"]

[rules.bearer-token]
description = "Bearer Token"
id = "bearer-token"
regex = '''(?i)bearer\s+[a-zA-Z0-9_\-\.=]+'''
tags = ["key", "token"]

[rules.safebreach-internal-env]
description = "SafeBreach Internal Environment Names"
id = "safebreach-internal-env"
regex = '''(?i)(flat-carp|zircon-piculet|pentest-demo|pentest01)'''
tags = ["internal", "environment", "SafeBreach"]

[allowlist]
description = "Global allowlist"
commits = []
paths = [
    '''\.secrets\.baseline''',
    '''\.pre-commit-config\.yaml''',
    '''safebreach_mcp_server\.egg-info/.*''',  # Allow package info
    '''\.vscode/set_env\.sh''',  # Allow private development file (git-ignored)
]
regexes = [
    '''your-secure-token-here''',
    '''your-auth-token-here''',
    '''your-secure-token''',
    '''your-token-here''',
    '''your-token''',
    '''REPLACE_WITH_ACTUAL_TOKEN''',
    '''<your-token-here>''',
    '''<your-api-key>''',
]